spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
      bindings:
        notifyOrders:
          group: customer-service
  output:
    ansi:
      enabled: ALWAYS
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
#  port: 8090
  port: 0

customer:
  name: spring-${server.port}
#  name: kevin

#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 500
#        read-timeout: 500

resilience4j:
  bulkhead:
    backends:
      order:
        maxConcurrentCall: 1
        maxWaitTime: 5
      menu:
        maxConcurrentCall: 5
        maxWaitTime: 5
  circuitbreaker:
    backends:
      order:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        event-consumer-buffer-size: 10
      menu:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        event-consumer-buffer-size: 10